### ISSUE TITLE
Video startup time is always 0 on tvOS

### ISSUE THREAD

**Issue by RomanPodymov** [Conviva/ConvivaAVFoundation#3]
Hello.
Thank you for ConvivaAVFoundation.
I am using ConvivaAVFoundation 4.0.7 in one of my iOS/tvOS apps. As I can see in the reports **Video startup time** is always 0 on tvOS and on iOS it is usually 4-6 seconds (that looks realistic). Could you please tell me why it can be 0? I am using `AVPlayer` to play videos.

**Comment by butchi-conviva** [comment]
Hello Roman,

Video Startup Time is calculated as the duration between reportPlaybackRequested api call and the first playing state of the player (which is auto detected by framework).

Could you please check below things to make sure integration is done correctly to calculate VST properly by SDK.

- reportPlaybackRequested  api is being called as soon as user clicks on Play button of the video
- call SetPlayer method with AVPlayer as argument before start playing the content

If you have implemented pre loading for the video, and if video starts playback immediately without buffering after reportPlaybackRequested call due to pre loading, this value would be reported as 0.

Please check if there is any difference in Conviva’s integration flow for iOS & tvOS platforms. The framework is same for both and ideally it should behave in the same way.
 
More details are available in [Integration instructions](https://community.conviva.com/site/one-sensor/sensors/ios/index_one_sensor.gsp) page.

If you still see the issue, please share the Touchstone trace. We will look into it and help further.

Thanks,
Butchi

**Comment by RomanPodymov** [comment]
Hello @butchi-conviva 
In my project `LivePass.createSession` was calling too late, thanks for your help.
